[package]
name = "voidchess_engine_rs"
version = "0.0.1"
authors = ["StephanS <simon.void+github@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tinyvec  = { version = "1.0.1", features = ["alloc"] }
