#!/bin/bash

echo "compiling to wasm module ..."
cd ./workspace/wasm/
wasm-pack build --no-default-features --release --target web

echo ""
echo "copying generated module from pkg to docs/src/engine ..."
cp -f ./pkg/package.json ./pkg/voidchess_engine* ../../docs/src/engine
